from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'src'/'gpt_windows_connector'

# Patch entitlements with role-based admin Pro+ and additive overrides.
p=SRC/'entitlements.py'; s=p.read_text(encoding='utf-8')
s=s.replace('    cancel_at_period_end: bool; bonus_requests: int; nodes_connected: int = 0','    cancel_at_period_end: bool; bonus_requests: int; nodes_connected: int = 0; bonus_nodes: int = 0; bonus_ai_accounts: int = 0; admin_grant: bool = False')
s=s.replace('"bonus_requests":self.bonus_requests,"can_buy_expansion"','"bonus_requests":self.bonus_requests,"bonus_nodes":self.bonus_nodes,"bonus_ai_accounts":self.bonus_ai_accounts,"admin_grant":self.admin_grant,"can_buy_expansion"')
marker='def _ensure_active_schema(db: sqlite3.Connection) -> None:\n'
helper='''def _ensure_entitlement_override_schema(db: sqlite3.Connection) -> None:\n    db.execute("""CREATE TABLE IF NOT EXISTS entitlement_overrides(\n        user_id TEXT PRIMARY KEY, bonus_requests INTEGER NOT NULL DEFAULT 0,\n        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        updated_at REAL NOT NULL DEFAULT 0\n    )""")\n\ndef _entitlement_override(db: sqlite3.Connection,user_id: str) -> tuple[int,int,int]:\n    _ensure_entitlement_override_schema(db)\n    row=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n    if not row: return 0,0,0\n    return max(0,int(row[0] or 0)),max(0,int(row[1] or 0)),max(0,int(row[2] or 0))\n\ndef _is_admin(db: sqlite3.Connection,user_id: str) -> bool:\n    try:\n        row=db.execute("SELECT role FROM users WHERE id=?",(user_id,)).fetchone()\n    except sqlite3.OperationalError:\n        return False\n    return bool(row and str(row[0]) in {"admin","super_admin"})\n\n'''
if helper not in s:
    s=s.replace(marker,helper+marker,1)
old='''        plan,status,expansion,bonus,pstart,pend,cancel,base=_plan_state(db,user_id,now)\n        req=_count(db,"SELECT COUNT(*) FROM task_steps WHERE owner_id=? AND started_at>=? AND started_at<?",(user_id,pstart,pend))\n        ai=_count(db,"SELECT COUNT(*) FROM oauth_client_users WHERE user_id=?",(user_id,))\n        node_limit=int(base["nodes"])+expansion*int(EXPANSION["nodes"])\n        connected=len(_bound_ids(db,user_id))\n        active=len(_sync_active(db,user_id,node_limit))\n    return Entitlements(plan,str(base["name"]),status if plan!="free" else "free",expansion,int(base["requests"])+expansion*int(EXPANSION["requests"])+bonus,node_limit,int(base["ai_accounts"])+expansion*int(EXPANSION["ai_accounts"]),req,active,ai,pstart,pend,pend if plan!="free" else None,cancel,bonus,connected)'''
new='''        plan,status,expansion,bonus,pstart,pend,cancel,base=_plan_state(db,user_id,now)\n        admin_grant=_is_admin(db,user_id)\n        if admin_grant:\n            plan="pro_plus"; status="admin"; expansion=0; base=PLANS["pro_plus"]\n            if pstart<=0 or pend<=pstart: pstart,pend=_free_period(now)\n        extra_requests,extra_nodes,extra_ai=_entitlement_override(db,user_id)\n        req=_count(db,"SELECT COUNT(*) FROM task_steps WHERE owner_id=? AND started_at>=? AND started_at<?",(user_id,pstart,pend))\n        ai=_count(db,"SELECT COUNT(*) FROM oauth_client_users WHERE user_id=?",(user_id,))\n        node_limit=int(base["nodes"])+expansion*int(EXPANSION["nodes"])+extra_nodes\n        connected=len(_bound_ids(db,user_id))\n        active=len(_sync_active(db,user_id,node_limit))\n    return Entitlements(plan,str(base["name"]),status if plan!="free" else "free",expansion,int(base["requests"])+expansion*int(EXPANSION["requests"])+bonus+extra_requests,node_limit,int(base["ai_accounts"])+expansion*int(EXPANSION["ai_accounts"])+extra_ai,req,active,ai,pstart,pend,pend if plan!="free" and not admin_grant else None,cancel,bonus,connected,extra_nodes,extra_ai,admin_grant)'''
if old not in s: raise SystemExit('snapshot block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Admin API: ensure override schema, expose effective plan, editable request/computer/AI grants.
p=SRC/'admin.py'; s=p.read_text(encoding='utf-8')
insert='''\ndef _ensure_entitlement_override_schema(db: sqlite3.Connection) -> None:\n    db.execute("""CREATE TABLE IF NOT EXISTS entitlement_overrides(\n        user_id TEXT PRIMARY KEY, bonus_requests INTEGER NOT NULL DEFAULT 0,\n        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        updated_at REAL NOT NULL DEFAULT 0\n    )""")\n\n'''
if insert not in s:
    s=s.replace('def _safe_details(raw: str | None) -> dict:\n',insert+'def _safe_details(raw: str | None) -> dict:\n',1)
s=s.replace('''            sub = db.execute("SELECT * FROM subscriptions WHERE user_id=?", (user_id,)).fetchone()''','''            sub = db.execute("SELECT * FROM subscriptions WHERE user_id=?", (user_id,)).fetchone()\n            _ensure_entitlement_override_schema(db)\n            override = db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()''',1)
s=s.replace('''        return JSONResponse({"user": dict(user), "subscription": dict(sub) if sub else {"plan":"free","status":"inactive"}, "entitlements":ent, "nodes": [dict(r) for r in nodes], "usage": dict(counts), "operations": [{**dict(r), "details": _safe_details(r["details"])} for r in ops]})''','''        return JSONResponse({"user": dict(user), "subscription": dict(sub) if sub else {"plan":"free","status":"inactive"}, "entitlements":ent, "admin_overrides":dict(override) if override else {"bonus_requests":0,"bonus_nodes":0,"bonus_ai_accounts":0}, "nodes": [dict(r) for r in nodes], "usage": dict(counts), "operations": [{**dict(r), "details": _safe_details(r["details"])} for r in ops]})''',1)
old='''            if "bonus_requests" in body:\n                bonus=max(0,int(body["bonus_requests"])); db.execute("UPDATE subscriptions SET bonus_requests=?,updated_at=? WHERE user_id=?",(bonus,now,user_id))'''
new='''            override_fields={k:max(0,int(body[k])) for k in ("bonus_requests","bonus_nodes","bonus_ai_accounts") if k in body}\n            if override_fields:\n                _ensure_entitlement_override_schema(db)\n                current=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n                values={"bonus_requests":int(current[0] or 0) if current else 0,"bonus_nodes":int(current[1] or 0) if current else 0,"bonus_ai_accounts":int(current[2] or 0) if current else 0}\n                values.update(override_fields)\n                db.execute("INSERT INTO entitlement_overrides(user_id,bonus_requests,bonus_nodes,bonus_ai_accounts,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET bonus_requests=excluded.bonus_requests,bonus_nodes=excluded.bonus_nodes,bonus_ai_accounts=excluded.bonus_ai_accounts,updated_at=excluded.updated_at",(user_id,values["bonus_requests"],values["bonus_nodes"],values["bonus_ai_accounts"],now))'''
if old not in s: raise SystemExit('admin bonus block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Admin UI: admins display effective Pro+ and can edit extra Requests / Computers / AI accounts.
p=SRC/'web_admin_runtime.py'; s=p.read_text(encoding='utf-8')
s=s.replace("body:JSON.stringify({status:adminDetailStatus.value,plan:adminDetailPlan.value,bonus_requests:+adminDetailBonus.value||0})","body:JSON.stringify({status:adminDetailStatus.value,plan:adminDetailPlan.value,bonus_requests:+adminDetailBonus.value||0,bonus_nodes:+adminDetailBonusNodes.value||0,bonus_ai_accounts:+adminDetailBonusAi.value||0})",1)
s=s.replace("${adminMetric(\\'Plan\\',d.subscription.plan)}","${adminMetric(\\'Plan\\',d.entitlements.admin_grant?\\'Pro+ · Admin\\':d.entitlements.plan_name)}",1)
s=s.replace('''<div><b>Bonus Requests</b><input id=\"adminDetailBonus\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc(d.entitlements.bonus_requests||0)}\"></div>''','''<div><b>Extra Requests</b><input id=\"adminDetailBonus\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc((d.admin_overrides||{}).bonus_requests||0)}\"></div><div><b>Extra Computers</b><input id=\"adminDetailBonusNodes\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc((d.admin_overrides||{}).bonus_nodes||0)}\"></div><div><b>Extra AI accounts</b><input id=\"adminDetailBonusAi\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc((d.admin_overrides||{}).bonus_ai_accounts||0)}\"></div>''',1)
p.write_text(s,encoding='utf-8')

# Tests.
p=ROOT/'tests'/'test_billing_entitlements.py'; s=p.read_text(encoding='utf-8')
append='''\n\ndef test_admin_is_effective_pro_plus_and_supports_extra_entitlements(tmp_path):\n    p=tmp_path/"db.sqlite"; schema(p)\n    with sqlite3.connect(p) as db:\n        db.execute("CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT)")\n        db.execute("INSERT INTO users VALUES(?,?)",("u","admin"))\n        db.execute("CREATE TABLE entitlement_overrides(user_id TEXT PRIMARY KEY,bonus_requests INTEGER,bonus_nodes INTEGER,bonus_ai_accounts INTEGER,updated_at REAL)")\n        db.execute("INSERT INTO entitlement_overrides VALUES(?,?,?,?,?)",("u",5000,2,4,time.time()))\n    e=snapshot(p,"u")\n    assert e.plan=="pro_plus" and e.admin_grant is True\n    assert e.request_limit==105000\n    assert e.node_limit==8\n    assert e.ai_account_limit==7\n\n'''
if 'test_admin_is_effective_pro_plus_and_supports_extra_entitlements' not in s:
    s += append
p.write_text(s,encoding='utf-8')

# Add admin API coverage.
p=ROOT/'tests'/'test_admin_entitlement_controls.py'
p.write_text('''import sqlite3\n\nfrom gpt_windows_connector.entitlements import snapshot\n\ndef test_non_admin_keeps_normal_plan(tmp_path):\n    p=tmp_path/"x.db"\n    with sqlite3.connect(p) as db:\n        db.execute("CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT)")\n        db.execute("INSERT INTO users VALUES('u','user')")\n        db.execute("CREATE TABLE subscriptions(user_id TEXT PRIMARY KEY,plan TEXT,status TEXT,expansion_quantity INTEGER DEFAULT 0,current_period_start REAL,current_period_end REAL,cancel_at_period_end INTEGER DEFAULT 0,bonus_requests INTEGER DEFAULT 0)")\n        db.execute("CREATE TABLE task_steps(id INTEGER PRIMARY KEY,owner_id TEXT,started_at REAL)")\n        db.execute("CREATE TABLE user_node_bindings(user_id TEXT,node_id TEXT,approved_at REAL)")\n        db.execute("CREATE TABLE oauth_client_users(client_id TEXT,user_id TEXT,authorized_at REAL)")\n    e=snapshot(p,'u')\n    assert e.plan=='free' and e.node_limit==1 and e.ai_account_limit==1\n''',encoding='utf-8')
print('admin entitlement controls applied')
