from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'src'/'gpt_windows_connector'
TESTS=ROOT/'tests'

# entitlements.py: add shared expiry for manual admin overrides and make active-node selection honor admin/extra node limits.
p=SRC/'entitlements.py'; s=p.read_text(encoding='utf-8')
s=s.replace('''        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        updated_at REAL NOT NULL DEFAULT 0\n    )""")\n\ndef _entitlement_override(db: sqlite3.Connection,user_id: str) -> tuple[int,int,int]:\n    _ensure_entitlement_override_schema(db)\n    row=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n    if not row: return 0,0,0\n    return max(0,int(row[0] or 0)),max(0,int(row[1] or 0)),max(0,int(row[2] or 0))\n''','''        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        expires_at REAL, updated_at REAL NOT NULL DEFAULT 0\n    )""")\n    cols={str(r[1]) for r in db.execute("PRAGMA table_info(entitlement_overrides)").fetchall()}\n    if "expires_at" not in cols:\n        db.execute("ALTER TABLE entitlement_overrides ADD COLUMN expires_at REAL")\n\ndef _entitlement_override(db: sqlite3.Connection,user_id: str,now: float|None=None) -> tuple[int,int,int,float|None,bool]:\n    _ensure_entitlement_override_schema(db)\n    row=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts,expires_at FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n    if not row: return 0,0,0,None,False\n    expires=float(row[3]) if row[3] not in (None,0,0.0) else None\n    expired=bool(expires is not None and expires <= float(now or time.time()))\n    if expired: return 0,0,0,expires,True\n    return max(0,int(row[0] or 0)),max(0,int(row[1] or 0)),max(0,int(row[2] or 0)),expires,False\n''')
s=s.replace('''        extra_requests,extra_nodes,extra_ai=_entitlement_override(db,user_id)\n''','''        extra_requests,extra_nodes,extra_ai,override_expires_at,override_expired=_entitlement_override(db,user_id,now)\n''')
s=s.replace('''        return {"plan":self.plan,"plan_name":self.plan_name,"status":self.status,"expansion_quantity":self.expansion_quantity,"request_limit":self.request_limit,"node_limit":self.node_limit,"ai_account_limit":self.ai_account_limit,"requests_used":self.requests_used,"nodes_used":self.nodes_used,"nodes_connected":self.nodes_connected,"ai_accounts_used":self.ai_accounts_used,"period_start":self.period_start,"period_end":self.period_end,"renewal_at":self.renewal_at,"cancel_at_period_end":self.cancel_at_period_end,"bonus_requests":self.bonus_requests,"bonus_nodes":self.bonus_nodes,"bonus_ai_accounts":self.bonus_ai_accounts,"admin_grant":self.admin_grant,"can_buy_expansion":self.can_buy_expansion,"request_remaining":max(0,self.request_limit-self.requests_used),"node_remaining":max(0,self.node_limit-self.nodes_used),"ai_account_remaining":max(0,self.ai_account_limit-self.ai_accounts_used)}\n''','''        return {"plan":self.plan,"plan_name":self.plan_name,"status":self.status,"expansion_quantity":self.expansion_quantity,"request_limit":self.request_limit,"node_limit":self.node_limit,"ai_account_limit":self.ai_account_limit,"requests_used":self.requests_used,"nodes_used":self.nodes_used,"nodes_connected":self.nodes_connected,"ai_accounts_used":self.ai_accounts_used,"period_start":self.period_start,"period_end":self.period_end,"renewal_at":self.renewal_at,"cancel_at_period_end":self.cancel_at_period_end,"bonus_requests":self.bonus_requests,"bonus_nodes":self.bonus_nodes,"bonus_ai_accounts":self.bonus_ai_accounts,"admin_grant":self.admin_grant,"can_buy_expansion":self.can_buy_expansion,"request_remaining":max(0,self.request_limit-self.requests_used),"node_remaining":max(0,self.node_limit-self.nodes_used),"ai_account_remaining":max(0,self.ai_account_limit-self.ai_accounts_used)}\n''')
# helper for effective node limit
anchor='''def active_node_ids(db_path: Path,user_id: str,preferred_node_ids: Iterable[str] | None=None) -> list[str]:\n'''
helper='''def _effective_node_limit(db: sqlite3.Connection,user_id: str,now: float) -> int:\n    plan,status,expansion,bonus,pstart,pend,cancel,base=_plan_state(db,user_id,now)\n    if _is_admin(db,user_id):\n        plan="pro_plus"; expansion=0; base=PLANS["pro_plus"]\n    _,extra_nodes,_,_,_=_entitlement_override(db,user_id,now)\n    return int(base["nodes"])+expansion*int(EXPANSION["nodes"])+extra_nodes\n\n'''
if helper not in s:
    if anchor not in s: raise SystemExit('active_node_ids marker missing')
    s=s.replace(anchor,helper+anchor,1)
s=s.replace('''    with _connect(db_path) as db:\n        plan,status,expansion,bonus,pstart,pend,cancel,base=_plan_state(db,user_id,now)\n        limit=int(base["nodes"])+expansion*int(EXPANSION["nodes"])\n        return _sync_active(db,user_id,limit,preferred_node_ids)\n\ndef set_active_node''','''    with _connect(db_path) as db:\n        limit=_effective_node_limit(db,user_id,now)\n        return _sync_active(db,user_id,limit,preferred_node_ids)\n\ndef set_active_node''',1)
s=s.replace('''    with _connect(db_path) as db:\n        plan,status,expansion,bonus,pstart,pend,cancel,base=_plan_state(db,user_id,now)\n        limit=int(base["nodes"])+expansion*int(EXPANSION["nodes"])\n        bound=set(_bound_ids(db,user_id))\n''','''    with _connect(db_path) as db:\n        limit=_effective_node_limit(db,user_id,now)\n        bound=set(_bound_ids(db,user_id))\n''',1)
p.write_text(s,encoding='utf-8')

# admin.py: expose expiry metadata and accept never/7d/30d/custom timestamp.
p=SRC/'admin.py'; s=p.read_text(encoding='utf-8')
s=s.replace('''        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        updated_at REAL NOT NULL DEFAULT 0\n    )""")\n''','''        bonus_nodes INTEGER NOT NULL DEFAULT 0, bonus_ai_accounts INTEGER NOT NULL DEFAULT 0,\n        expires_at REAL, updated_at REAL NOT NULL DEFAULT 0\n    )""")\n    cols={str(r[1]) for r in db.execute("PRAGMA table_info(entitlement_overrides)").fetchall()}\n    if "expires_at" not in cols:\n        db.execute("ALTER TABLE entitlement_overrides ADD COLUMN expires_at REAL")\n''')
s=s.replace('''            override = db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n''','''            override = db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts,expires_at,updated_at FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n''')
s=s.replace('''        return JSONResponse({"user": dict(user), "subscription": dict(sub) if sub else {"plan":"free","status":"inactive"}, "entitlements":ent, "admin_overrides":dict(override) if override else {"bonus_requests":0,"bonus_nodes":0,"bonus_ai_accounts":0}, "nodes": [dict(r) for r in nodes], "usage": dict(counts), "operations": [{**dict(r), "details": _safe_details(r["details"])} for r in ops]})\n''','''        override_data=dict(override) if override else {"bonus_requests":0,"bonus_nodes":0,"bonus_ai_accounts":0,"expires_at":None,"updated_at":None}\n        override_data["expired"]=bool(override_data.get("expires_at") and float(override_data["expires_at"])<=time.time())\n        return JSONResponse({"user": dict(user), "subscription": dict(sub) if sub else {"plan":"free","status":"inactive"}, "entitlements":ent, "admin_overrides":override_data, "nodes": [dict(r) for r in nodes], "usage": dict(counts), "operations": [{**dict(r), "details": _safe_details(r["details"])} for r in ops]})\n''')
old='''            override_fields={k:max(0,int(body[k])) for k in ("bonus_requests","bonus_nodes","bonus_ai_accounts") if k in body}\n            if override_fields:\n                _ensure_entitlement_override_schema(db)\n                current=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n                values={"bonus_requests":int(current[0] or 0) if current else 0,"bonus_nodes":int(current[1] or 0) if current else 0,"bonus_ai_accounts":int(current[2] or 0) if current else 0}\n                values.update(override_fields)\n                db.execute("INSERT INTO entitlement_overrides(user_id,bonus_requests,bonus_nodes,bonus_ai_accounts,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET bonus_requests=excluded.bonus_requests,bonus_nodes=excluded.bonus_nodes,bonus_ai_accounts=excluded.bonus_ai_accounts,updated_at=excluded.updated_at",(user_id,values["bonus_requests"],values["bonus_nodes"],values["bonus_ai_accounts"],now))\n'''
new='''            override_fields={k:max(0,int(body[k])) for k in ("bonus_requests","bonus_nodes","bonus_ai_accounts") if k in body}\n            expiry_supplied="override_expires_at" in body\n            if override_fields or expiry_supplied:\n                _ensure_entitlement_override_schema(db)\n                current=db.execute("SELECT bonus_requests,bonus_nodes,bonus_ai_accounts,expires_at FROM entitlement_overrides WHERE user_id=?",(user_id,)).fetchone()\n                values={"bonus_requests":int(current[0] or 0) if current else 0,"bonus_nodes":int(current[1] or 0) if current else 0,"bonus_ai_accounts":int(current[2] or 0) if current else 0}\n                values.update(override_fields)\n                expires=(float(current[3]) if current and current[3] not in (None,0,0.0) else None)\n                if expiry_supplied:\n                    raw=body.get("override_expires_at")\n                    expires=None if raw in (None,"",0,0.0) else float(raw)\n                    if expires is not None and expires <= now: raise ValueError("Expiration must be in the future")\n                if not any(values.values()): expires=None\n                db.execute("INSERT INTO entitlement_overrides(user_id,bonus_requests,bonus_nodes,bonus_ai_accounts,expires_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET bonus_requests=excluded.bonus_requests,bonus_nodes=excluded.bonus_nodes,bonus_ai_accounts=excluded.bonus_ai_accounts,expires_at=excluded.expires_at,updated_at=excluded.updated_at",(user_id,values["bonus_requests"],values["bonus_nodes"],values["bonus_ai_accounts"],expires,now))\n'''
if old not in s: raise SystemExit('admin override update marker missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# Web admin: expiry presets and custom datetime. Keep all override controls in one card.
p=SRC/'web_admin_runtime.py'; s=p.read_text(encoding='utf-8')
old="async function saveAdminUser(id){await api(\\'/api/admin/users/\\'+encodeURIComponent(id),{method:\\'PUT\\',body:JSON.stringify({status:adminDetailStatus.value,plan:adminDetailPlan.value,bonus_requests:+adminDetailBonus.value||0,bonus_nodes:+adminDetailBonusNodes.value||0,bonus_ai_accounts:+adminDetailBonusAi.value||0})});toast(\\'User updated\\');await showAdminUser(id)}"
new="function adminExpiryValue(){const mode=adminDetailExpiry.value;if(mode===\\'never\\')return null;if(mode===\\'7d\\')return Date.now()/1000+7*86400;if(mode===\\'30d\\')return Date.now()/1000+30*86400;if(mode===\\'custom\\'){const v=adminDetailExpiryCustom.value;if(!v)throw new Error(\\'Choose an expiration date\\');return new Date(v).getTime()/1000}return null}\\nfunction adminExpiryModeChange(){if(window.adminDetailExpiryCustom)adminDetailExpiryCustom.classList.toggle(\\'hidden\\',adminDetailExpiry.value!==\\'custom\\')}\\nasync function saveAdminUser(id){try{await api(\\'/api/admin/users/\\'+encodeURIComponent(id),{method:\\'PUT\\',body:JSON.stringify({status:adminDetailStatus.value,plan:adminDetailPlan.value,bonus_requests:+adminDetailBonus.value||0,bonus_nodes:+adminDetailBonusNodes.value||0,bonus_ai_accounts:+adminDetailBonusAi.value||0,override_expires_at:adminExpiryValue()})});toast(\\'User updated\\');await showAdminUser(id)}catch(e){toast(e.message)}}"
if old not in s: raise SystemExit('web saveAdminUser marker missing')
s=s.replace(old,new,1)
old_fragment="<div><b>Extra AI accounts</b><input id=\"adminDetailBonusAi\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc((d.admin_overrides||{}).bonus_ai_accounts||0)}\"></div></div><div class=\"actions\"><button class=\"btn primary\" onclick=\"saveAdminUser(\\'${u.id}\\')\">Save account</button></div>"
new_fragment="<div><b>Extra AI accounts</b><input id=\"adminDetailBonusAi\" class=\"input\" type=\"number\" min=\"0\" value=\"${esc((d.admin_overrides||{}).bonus_ai_accounts||0)}\"></div><div><b>Extra quota expires</b><select id=\"adminDetailExpiry\" onchange=\"adminExpiryModeChange()\"><option value=\"never\">Never</option><option value=\"7d\">7 days</option><option value=\"30d\">30 days</option><option value=\"custom\">Custom</option></select><input id=\"adminDetailExpiryCustom\" class=\"input hidden\" type=\"datetime-local\"></div></div><div class=\"muted\" style=\"margin-top:10px\">${d.admin_overrides?.expired?\'Extra quota expired\':(d.admin_overrides?.expires_at?\'Extra quota expires \'+new Date(d.admin_overrides.expires_at*1000).toLocaleString():\'Extra quota does not expire\')}</div><div class=\"actions\"><button class=\"btn primary\" onclick=\"saveAdminUser(\\'${u.id}\\')\">Save account</button></div>"
if old_fragment not in s: raise SystemExit('web override UI marker missing')
s=s.replace(old_fragment,new_fragment,1)
# After modal opens, initialize custom date if an expiry already exists.
old_tail="`;adminUserModal.classList.remove(\\'hidden\\')}"
new_tail="`;adminUserModal.classList.remove(\\'hidden\\');if(d.admin_overrides?.expires_at){adminDetailExpiry.value=\\'custom\\';adminDetailExpiryCustom.classList.remove(\\'hidden\\');const dt=new Date(d.admin_overrides.expires_at*1000);adminDetailExpiryCustom.value=new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16)}}"
if old_tail not in s: raise SystemExit('web modal tail marker missing')
s=s.replace(old_tail,new_tail,1)
p.write_text(s,encoding='utf-8')

# Regression tests.
test=TESTS/'test_admin_entitlement_expiry.py'
test.write_text('''import sqlite3\nimport time\n\nfrom gpt_windows_connector.entitlements import active_node_ids, snapshot\n\n\ndef schema(path):\n    with sqlite3.connect(path) as db:\n        db.executescript("""\n        CREATE TABLE subscriptions(user_id TEXT PRIMARY KEY,plan TEXT,status TEXT,expansion_quantity INTEGER DEFAULT 0,current_period_start REAL,current_period_end REAL,cancel_at_period_end INTEGER DEFAULT 0,bonus_requests INTEGER DEFAULT 0);\n        CREATE TABLE task_steps(id INTEGER PRIMARY KEY,owner_id TEXT,started_at REAL);\n        CREATE TABLE user_node_bindings(user_id TEXT,node_id TEXT,approved_at REAL);\n        CREATE TABLE oauth_client_users(client_id TEXT,user_id TEXT,authorized_at REAL);\n        CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT);\n        CREATE TABLE entitlement_overrides(user_id TEXT PRIMARY KEY,bonus_requests INTEGER DEFAULT 0,bonus_nodes INTEGER DEFAULT 0,bonus_ai_accounts INTEGER DEFAULT 0,expires_at REAL,updated_at REAL DEFAULT 0);\n        """)\n\ndef test_unexpired_override_applies_and_expired_override_is_ignored(tmp_path):\n    p=tmp_path/'db.sqlite'; schema(p); now=time.time()\n    with sqlite3.connect(p) as db:\n        db.execute("INSERT INTO users VALUES('u','user')")\n        db.execute("INSERT INTO entitlement_overrides VALUES('u',5000,2,1,?,?)",(now+3600,now))\n    e=snapshot(p,'u',now)\n    assert (e.request_limit,e.node_limit,e.ai_account_limit)==(6000,3,2)\n    e2=snapshot(p,'u',now+7200)\n    assert (e2.request_limit,e2.node_limit,e2.ai_account_limit)==(1000,1,1)\n\ndef test_admin_pro_plus_and_extra_nodes_drive_active_selection(tmp_path):\n    p=tmp_path/'db.sqlite'; schema(p); now=time.time()\n    with sqlite3.connect(p) as db:\n        db.execute("INSERT INTO users VALUES('a','admin')")\n        db.execute("INSERT INTO entitlement_overrides VALUES('a',1000,2,1,NULL,?)",(now,))\n        db.executemany("INSERT INTO user_node_bindings VALUES('a',?,?)",[(f'n{i}',now+i) for i in range(8)])\n    e=snapshot(p,'a',now)\n    assert e.admin_grant and e.plan=='pro_plus'\n    assert (e.request_limit,e.node_limit,e.ai_account_limit)==(101000,8,4)\n    assert len(active_node_ids(p,'a'))==8\n''',encoding='utf-8')
print('admin entitlement expiry optimization applied')
